version: '3'
services:
  asterisk:
    image: node-open-cc-asterisk:latest
    build: ./packages/asterisk
    environment:
      - MOH_STREAM=http://146.71.124.10:8100/stream
      - SIP_PROXY_IPV4=${KAMAILIO_PRIVATE_IPV4}
      - ARI_PASSWORD=${MACHINE_KEY}
      - RTP_PORTS=10001-10100
    network_mode: host
  stasis_app:
    image: node-open-cc-packages:latest
    build: .
    environment:
      - SERVICES=/opt/app/examples/stasis-app/src/index.ts
      - ASTERISK_URL=http://$${process.env.HOST_DOCKER_INTERNAL}:8088
      - ASTERISK_CREDS=ariUser:${MACHINE_KEY}
      - NATS_SERVERS=nats://${KAMAILIO_PRIVATE_IPV4}:4222
      - DISPATCH_ADDRESS=sip:${PRIVATE_IPV4}:5060
      - DEBUG=api-container:*
    depends_on:
      - asterisk
  interaction_api:
    image: node-open-cc-packages:latest
    environment:
      - SERVICES=/opt/app/packages/core-api/src/interaction/index.ts
      - NATS_SERVERS=nats://${KAMAILIO_PRIVATE_IPV4}:4222
      - DEBUG=api-container:*
    ports:
      - 8080:8080
  routing_api:
    image: node-open-cc-packages:latest
    environment:
      - SERVICES=/opt/app/packages/core-api/src/routing/index.ts
      - NATS_SERVERS=nats://${KAMAILIO_PRIVATE_IPV4}:4222
      - DEBUG=api-container:*