version: '3'
services:
  kamailio:
    image: node-open-cc-kamailio-proxy:latest
    build: ./packages/kamailio-proxy
    volumes:
    - ./packages/kamailio-proxy/files/etc/kamailio/kamailio.cfg:/etc/kamailio/kamailio.cfg
    network_mode: host
  kamailio-agent:
    image: node-open-cc-packages:latest
    build: .
    environment:
      - SERVICES=/opt/app/packages/kamailio-agent/index.ts
      - KAMAILIO_URL=http://${PRIVATE_IPV4}:5060
      - CLUSTER_HOST=${PRIVATE_IPV4}
      - CLUSTER_NETWORKS=kamailionet
      - DEBUG=api-container:*
    depends_on:
      - kamailio
    network_mode: host