version: '3.7'
services:
  example_flow:
    image: node-open-cc-packages:latest
    environment:
      - SERVICES=/opt/app/packages/flow-agent/index.ts
      - NATS_SERVERS=nats://${NATS_PRIVATE_IPV4}:4222
      - FLOW=/opt/app/examples/flow/flow.gliffy
      - DEBUG=${DEBUG:-api-container:*}
      - DEBUG_COLORS=true