version: '3'
services:
  kamailio:
    image: node-open-cc-kamailio-proxy:latest
    build: ./packages/kamailio-proxy
    volumes:
    - ./packages/kamailio-proxy/files/etc/kamailio/kamailio.cfg:/etc/kamailio/kamailio.cfg
    network_mode: host
  kamailio-agent:
    image: node-open-cc-packages:latest
    build: .
    environment:
      - SERVICES=/opt/app/packages/kamailio-agent/index.ts
      - KAMAILIO_URL=http://${PRIVATE_IPV4}:5060
      - NATS_SERVERS=nats://${PRIVATE_IPV4}:4222
      - DEBUG=api-container:*
    depends_on:
      - kamailio
    network_mode: host
  nats:
    image: nats:alpine3.11
    ports:
      - 4222:4222