version: '3'
services:
  asterisk:
    image: node-open-cc-asterisk:latest
    build: ./examples/stasis-app
    volumes:
      - "./examples/stasis-app/etc/asterisk/ari.conf:/etc/asterisk/ari.conf"
      - "./examples/stasis-app/etc/asterisk/extensions.conf:/etc/asterisk/extensions.conf"
      - "./examples/stasis-app/etc/asterisk/http.conf:/etc/asterisk/http.conf"
      - "./examples/stasis-app/etc/asterisk/modules.conf:/etc/asterisk/modules.conf"
      # - "./examples/stasis-app/etc/asterisk/pjsip.conf:/etc/asterisk/pjsip.conf"
      - "./examples/stasis-app/etc/asterisk/rtp.conf:/etc/asterisk/rtp.conf"
      - "./examples/stasis-app/etc/asterisk/sip.conf:/etc/asterisk/sip.conf"
      - "./examples/stasis-app/etc/asterisk/musiconhold.conf:/etc/asterisk/musiconhold.conf"
    environment:
      - MOH_STREAM=http://146.71.124.10:8100/stream
    network_mode: host
  stasis_app:
    image: node-open-cc-packages:latest
    build: .
    environment:
      - SERVICES=/opt/app/examples/stasis-app/src/index.ts
      - ASTERISK_URL=http://$${process.env.HOST_DOCKER_INTERNAL}:8088
      - ASTERISK_CREDS=ariUser:ariPassword
      - SEEDS=192.168.188.110:9742
      - CLUSTER_HOST=192.168.188.111
      - DISPATCH_ADDRESS=sip:192.168.188.111:5060
      - CLUSTER_NETWORKS=kamailionet,statisappnet
      - DEBUG=api-container:*
    depends_on:
      - asterisk
    ports:
      - 9742:9742
  interaction_api:
    image: node-open-cc-packages:latest
    environment:
      - SERVICES=/opt/app/packages/core-api/src/interaction/index.ts
      - CLUSTER_NETWORKS=statisappnet
      - SEEDS=192.168.188.111:9742
      - DEBUG=api-container:*
    ports:
      - 8080:8080
  routing_api:
    image: node-open-cc-packages:latest
    environment:
      - SERVICES=/opt/app/packages/core-api/src/routing/index.ts
      - CLUSTER_NETWORKS=statisappnet
      - SEEDS=192.168.188.111:9742
      - DEBUG=api-container:*