version: '3'
services:
  asterisk:
    image: dougbtv/asterisk13
    volumes:
      - "./stasis-app/etc/asterisk/ari.conf:/etc/asterisk/ari.conf"
      - "./stasis-app/etc/asterisk/extensions.conf:/etc/asterisk/extensions.conf"
      - "./stasis-app/etc/asterisk/http.conf:/etc/asterisk/http.conf"
      - "./stasis-app/etc/asterisk/modules.conf:/etc/asterisk/modules.conf"
      - "./stasis-app/etc/asterisk/pjsip.conf:/etc/asterisk/pjsip.conf"
      - "./stasis-app/etc/asterisk/rtp.conf:/etc/asterisk/rtp.conf"
      - "./stasis-app/etc/asterisk/sip.conf:/etc/asterisk/sip.conf"
    ports:
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "10001-10100:10001-10100/udp"
    network_mode: host
  stasis_app:
    image: node-open-cc-packages:latest
    build:
      context: ../
      dockerfile: examples/Dockerfile
    environment:
      - SERVICES=/opt/app/examples/stasis-app/dist/src/index.js
      - ASTERISK_URL=http://$${process.env.HOST_DOCKER_INTERNAL}:8088
      - ASTERISK_CREDS=ariUser:ariPassword
      - DEBUG=api-container:*,-api-container:container
    volumes:
      - "../:/opt/dev"
    ports:
      - "8080:8080"
  interaction_api:
    image: node-open-cc-packages:latest
    environment:
      - SERVICES=/opt/app/packages/interaction-api/dist/src/index.js
      - SEEDS=stasis_app:9742
      - DEBUG=api-container:*,-api-container:container
    volumes:
      - "../:/opt/dev"
  routing_api:
    image: node-open-cc-packages:latest
    environment:
      - SERVICES=/opt/app/packages/routing-api/dist/src/index.js
      - SEEDS=stasis_app:9742
      - DEBUG=api-container:*,-api-container:container
    volumes:
      - "../:/opt/dev"