version: '3'
services:
  asterisk:
    image: dougbtv/asterisk14
    volumes:
      - "./etc/asterisk:/etc/asterisk"
    ports:
      - "5060:5060/udp"
      - "10000-10101:10000-10101/udp"
  stasis_app:
    image: node-open-cc-packages:latest
    build:
      context: ../../
      dockerfile: examples/Dockerfile
    environment:
      - ASTERISK_URL=http://asterisk:8088
      - ASTERISK_CREDS=ariUser:ariPassword
    volumes:
      - "./:/opt/service"
    ports:
      - "8080:8080"
  interaction_api:
    image: node-open-cc-packages:latest
    environment:
      - SEEDS=stasis_app:9742
    volumes:
      - "../../packages/interaction-api:/opt/service"
  routing_api:
    image: node-open-cc-packages:latest
    environment:
      - SEEDS=stasis_app:9742
    volumes:
      - "../../packages/routing-api:/opt/service"