version: '3'
services:
  asterisk:
    image: dougbtv/asterisk14
    volumes:
      - "./etc/asterisk:/etc/asterisk"
    ports:
      - "5060:5060/udp"
      - "10000-10101:10000-10101/udp"
  stasis_app:
    image: node-open-cc-packages:latest
    build:
      context: ../../
      dockerfile: examples/Dockerfile
    command: ["node", "./packages/api-container/src/index.js"]
    environment:
      - ASTERISK_URL=http://asterisk:8088
      - ASTERISK_CREDS=ariUser:ariPassword
      - SERVICES=/opt/app/examples/stasis-app/host
    volumes:
      - "./:/opt/app/examples/stasis-app/host"
    ports:
      - "8080:8080"
  interaction_api:
    image: node-open-cc-packages:latest
    command: ["node", "./packages/api-container/src/index.js"]
    environment:
      - SERVICES=/opt/app/packages/interaction-api/host
      - SEEDS=stasis_app:9742
    volumes:
      - "./../../packages/interaction-api:/opt/app/packages/interaction-api/host"